#!/bin/bash
# Build Sweep.app bundle (local profile) and sign with the stable self-signed cert
# so TCC grants (FDA later) survive rebuilds. See macos-native-tool skill, Recipe 1+2.
#
# PLAN §2 Helper contract: SweepHelper's XPC listener trusts callers by
# `identifier "com.aditya.sweep" and certificate leaf = H"<hash>"` — Sweep.app's own bundle
# identifier AND the signing cert's leaf fingerprint, with no anchor clause. Both the identifier
# and the hash have to be baked into the helper's binary *before* it is compiled (Swift has no
# runtime way to ask "what cert is about to sign me, and as whom"), so the order here is fixed and
# load-bearing:
#
#   1. Sign a disposable probe file with $CERT, exactly the identity that will sign both real
#      binaries, and read its leaf hash back via `codesign -d -r-`.
#   2. Regenerate SweepHelper's `GeneratedHelperTrust.swift` with that hash and Sweep.app's bundle
#      identifier ($APP_BUNDLE_IDENTIFIER, the same value baked into the Info.plist below — one
#      shell variable, two consumers, so they can never drift apart) — BEFORE `swift build` ever
#      compiles the helper target.
#   3. `swift build -c release`, which now bakes the real hash and identifier into the SweepHelper
#      binary.
#   4. Sign inside-out: helper binary first, then the app bundle that contains it (a bundle's seal
#      must be applied last, after every nested item it covers already has its own).
#   5. Verify both designated requirements are cert-based AND identifier-bound to
#      $APP_BUNDLE_IDENTIFIER, exactly like the pre-helper check below already did for the app
#      alone — Codex finding #1: a certificate-only requirement is satisfied by any binary this
#      machine's signing cert has ever signed, not just Sweep.app.
set -euo pipefail
cd "$(dirname "$0")/.."

CERT="${SWEEP_CERT:-Nodu Sim Local Signer}"
APP_BUNDLE_IDENTIFIER="com.aditya.sweep"
APP="$HOME/Applications/Sweep.app"
HELPER_TRUST_FILE="SweepHelper/Sources/SweepHelper/GeneratedHelperTrust.swift"
HELPER_TRUST_LEAF_PLACEHOLDER="UNSET-PLACEHOLDER-REPLACED-BY-scripts-build-app-sh"
HELPER_TRUST_IDENTIFIER_PLACEHOLDER="UNSET PLACEHOLDER - REPLACED BY scripts/build-app.sh"

# --- 1. Extract the signing cert's leaf hash ------------------------------------------------

PROBE_DIR="$(mktemp -d)"
PROBE_FILE="$PROBE_DIR/cert-probe"
trap 'rm -rf "$PROBE_DIR"' EXIT
touch "$PROBE_FILE"
codesign --force --sign "$CERT" --timestamp=none "$PROBE_FILE" >/dev/null 2>&1

CERT_LEAF_HASH="$(codesign -d -r- "$PROBE_FILE" 2>&1 \
  | grep -o 'certificate leaf = H"[0-9a-fA-F]\{40\}"' \
  | sed -E 's/certificate leaf = H"([0-9a-fA-F]+)"/\1/')"

if [ -z "$CERT_LEAF_HASH" ]; then
  echo "ERROR: could not extract a certificate leaf hash from '$CERT'. Refusing to build the helper."
  exit 1
fi
echo "Signing cert leaf hash: $CERT_LEAF_HASH"
echo "App bundle identifier: $APP_BUNDLE_IDENTIFIER"

# --- 2. Inject both into the helper target, before compiling --------------------------------

cat > "$HELPER_TRUST_FILE" <<SWIFT
/// GENERATED by scripts/build-app.sh — do not hand-edit. Restored to rejecting placeholders by
/// this same script's cleanup step once the release binaries are built and verified below, so a
/// plain \`swift build\`/\`swift test\` never picks up a real cert hash or app identifier. See
/// GeneratedHelperTrust's checked-in doc comment for why the placeholders themselves must always
/// fail \`HelperTrust.isValidLeafHash\`/\`isValidAppIdentifier\`.
enum GeneratedHelperTrust {
    static let designatedRequirementLeafHash = "$CERT_LEAF_HASH"
    static let designatedRequirementAppIdentifier = "$APP_BUNDLE_IDENTIFIER"
}
SWIFT

# Verify the injection landed in source, before it is ever compiled in — deterministic and
# independent of whether the code-signing identity used below even exists (unlike the
# codesign-based checks in step 5, which need a real signing identity to run at all).
if ! grep -q "designatedRequirementLeafHash = \"$CERT_LEAF_HASH\"" "$HELPER_TRUST_FILE" \
  || ! grep -q "designatedRequirementAppIdentifier = \"$APP_BUNDLE_IDENTIFIER\"" "$HELPER_TRUST_FILE"; then
  echo "ERROR: failed to inject the cert hash / app identifier into $HELPER_TRUST_FILE"
  exit 1
fi

restore_placeholder() {
  cat > "$HELPER_TRUST_FILE" <<SWIFT
/// Overwritten by \`scripts/build-app.sh\` immediately before it builds the release helper: the
/// signing cert's leaf-certificate SHA-1 hash and Sweep.app's own bundle identifier, both read
/// back from the just-signed app bundle via \`codesign -d -r-\` on a probe file / the app itself,
/// signed with the exact same identity that then signs both \`SweepApp\` and \`SweepHelper\`
/// (build order: extract hash -> regenerate this file -> \`swift build\` -> sign helper -> sign app,
/// so the values embedded here are always the ones the shipped binaries actually carry).
///
/// \`designatedRequirementAppIdentifier\` is Sweep.app's identifier — never the helper binary's own
/// (a bare Mach-O executable's inferred identifier defaults to its filename, \`SweepHelper\`, which
/// is exactly the wrong thing to trust: see \`HelperTrust.designatedRequirement\`'s doc comment,
/// Codex finding #1).
///
/// Checked in with placeholders that \`HelperTrust.isValidLeafHash\`/\`isValidAppIdentifier\` always
/// reject, so a helper built any other way — a plain \`swift build\`, CI, \`swift test\` — refuses to
/// start (\`main.swift\`'s very first gates) rather than stand up an \`NSXPCListener\` trusting
/// nothing, or worse, trusting everything.
enum GeneratedHelperTrust {
    static let designatedRequirementLeafHash = "$HELPER_TRUST_LEAF_PLACEHOLDER"
    static let designatedRequirementAppIdentifier = "$HELPER_TRUST_IDENTIFIER_PLACEHOLDER"
}
SWIFT
}
# Runs on every exit path (success, build failure, verification failure) so a failed release build
# never leaves a real cert hash sitting in a tracked source file.
trap 'rm -rf "$PROBE_DIR"; restore_placeholder' EXIT

# --- 3. Build both binaries with the real hash baked into the helper ------------------------

swift build -c release
APP_BIN=".build/release/SweepApp"
HELPER_BIN=".build/release/SweepHelper"

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" "$APP/Contents/Library/LaunchDaemons"
cp "$APP_BIN" "$APP/Contents/MacOS/Sweep"
cp "$HELPER_BIN" "$APP/Contents/MacOS/SweepHelper"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleExecutable</key><string>Sweep</string>
  <key>CFBundleIdentifier</key><string>$APP_BUNDLE_IDENTIFIER</string>
  <key>CFBundleName</key><string>Sweep</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSMinimumSystemVersion</key><string>15.0</string>
  <!-- AppCleaner-parity drop targets (PLAN §3 module 5): a .app dragged onto Sweep's Dock icon
       while it is closed launches the process, and Launch Services hands the dropped bundle to
       SweepAppDelegate.application(_:open:) as a document-open event. LSHandlerRank "Alternate"
       registers Sweep as *able* to open application bundles without claiming the double-click
       default (that stays Finder/LaunchServices' own "open the app" behavior). -->
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key><string>Application</string>
      <key>CFBundleTypeRole</key><string>Viewer</string>
      <key>LSHandlerRank</key><string>Alternate</string>
      <key>LSItemContentTypes</key>
      <array><string>com.apple.application-bundle</string></array>
    </dict>
  </array>
  <!-- sweep://open-uninstall-orphan?bundleID=... — the SmartDelete watcher's own offer-accept
       deep link (TrashOfferPanel), delivered back to the running process via .onOpenURL. -->
  <key>CFBundleURLTypes</key>
  <array>
    <dict>
      <key>CFBundleURLName</key><string>com.aditya.sweep.deeplink</string>
      <key>CFBundleURLSchemes</key>
      <array><string>sweep</string></array>
    </dict>
  </array>
</dict></plist>
PLIST

# PLAN Appendix B: the LaunchDaemon plist must live inside the app bundle at
# Contents/Library/LaunchDaemons (never copied to /Library/LaunchDaemons by hand), and
# BundleProgram is the app-bundle-relative path SMAppService resolves at registration time —
# nothing here names an absolute path baked in at build time, so the bundle can move.
cat > "$APP/Contents/Library/LaunchDaemons/com.aditya.sweep.helper.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.aditya.sweep.helper</string>
  <key>BundleProgram</key><string>Contents/MacOS/SweepHelper</string>
  <key>MachServices</key>
  <dict>
    <key>com.aditya.sweep.helper</key><true/>
  </dict>
</dict></plist>
PLIST

# Bundle the rule catalog read-only (Codex finding #10).
mkdir -p "$APP/Contents/Resources/rules"
cp rules/schema.json "$APP/Contents/Resources/rules/"
[ -f rules/catalog.json ] && cp rules/catalog.json "$APP/Contents/Resources/rules/" || true

# --- 4. Sign inside-out: helper first, then the app bundle that now contains it --------------

codesign --force --sign "$CERT" --timestamp=none "$APP/Contents/MacOS/SweepHelper"
codesign --force --sign "$CERT" --timestamp=none "$APP"

# --- 5. Verify both designated requirements are cert-based, and the app's is identifier-bound ---

verify_cert_based_dr() {
  local label="$1" target="$2"
  if codesign -d -r- "$target" 2>&1 | grep -q "certificate leaf"; then
    echo "$label signed with stable identity: OK"
  else
    echo "ERROR: $label's designated requirement is not cert-based; TCC grants / helper trust will not persist"
    exit 1
  fi
}
verify_cert_based_dr "App" "$APP"
verify_cert_based_dr "Helper" "$APP/Contents/MacOS/SweepHelper"

# codesign's own default designated requirement for a bundle with an Info.plist already binds the
# identifier (verified against this machine's real Sweep.app: `identifier "com.aditya.sweep" and
# certificate leaf = H"…"`) — this is the exact requirement language SweepHelper's
# `setConnectionCodeSigningRequirement` call is built to also require of its caller (Codex
# finding #1: a cert-only requirement would accept any binary $CERT has ever signed, not just
# Sweep.app). Checked explicitly here so this never silently regresses to cert-only while the
# check above keeps passing.
if ! codesign -d -r- "$APP" 2>&1 | grep -q "identifier \"$APP_BUNDLE_IDENTIFIER\""; then
  echo "ERROR: App's designated requirement is not bound to identifier \"$APP_BUNDLE_IDENTIFIER\""
  exit 1
fi
echo "App designated requirement is identifier-bound to $APP_BUNDLE_IDENTIFIER: OK"

/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP"
echo "Built: $APP (helper embedded, not registered — SMAppService registration happens lazily at first Maintenance use)"
